### ISSUE TITLE
could not find entry point in sklearn_logisic_regression example

### ISSUE THREAD

**Issue by Amarchuk** [mlflow/mlflow#1094]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no, trying to use `sklearn_logisic_regression` example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**:0.9.0
- **Python version**: 3.6.6, also try 3.5.2
- **npm version (if running the dev UI): -
- **Exact command to reproduce**: `mlflow run sklearn_logistic_regression/train.py --no-conda` or `mlflow run sklearn_logistic_regression --no-conda`

### Describe the problem
I try to update my own project for mlflow usage, but got an exception, then I go to examples and see the same exception. After run `mlflow run sklearn_logistic_regression --no-conda` I got
```bash
/lib/python3.6/site-packages/mlflow/utils/environment.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env = yaml.load(_conda_header)
2019/04/03 22:13:35 ERROR mlflow.cli: === Could not find main among entry points [] or interpret main as a runnable script. Supported script file extensions: ['.py', '.sh'] ===
```
Note that I try to work without `conda`. Warning sometimes appears, sometimes not. Did I miss something?

Thanks.

P.S. `mlflow run sklearn_elasticnet_wine -P alpha=0.5 --no-conda` works fine

**Comment by PMende** [comment]
I'm getting a similar error trying to write my own example from scratch. The [documentation](https://www.mlflow.org/docs/latest/projects.html) suggests that it is optional to have an entry point named `main`. If this isn't the case, you should update the documentation to reflect this.

**Comment by zhangruiskyline** [comment]
I am getting same issue, I have 3 steps in workflow, one is shell script, and other two are python script, they can be run separately, but somehow when define a workstep, always get same error as above

**Comment by aneeshvartakavi** [comment]
I'm getting the same error trying to reproduce the official example [here](https://github.com/mlflow/mlflow/tree/master/examples/docker). I'm running mlflow version `1.3.0` installed from pip, on ubuntu 18.04, using python 3.7 (anaconda).

Command: 
`mlflow run . -P alpha=0.5`

Result:
```
ERROR mlflow.cli: === Could not find main among entry points [] or interpret main as a runnable script. Supported script file extensions: ['.py', '.sh'] ===
```
I've tried using the `-no-conda` flag, and get the same output as above.

**Comment by smurching** [comment]
Hi all, apologies for the delayed response - as @aneeshvartakavi mentioned, this issue can be caused by our previously case-sensitive detection of MLproject files, which was fixed in https://github.com/mlflow/mlflow/pull/1981 (i.e. upgrading to MLflow 1.4 should resolve the issue in many cases)

**Comment by dbczumar** [comment]
@Amarchuk it appears that this issue was fixed in MLflow 1.4; we now have CI for our examples, and they seem to be executing successfully as of 3/6/20. Please feel free to reopen this issue if you're still running into problems!

**Comment by ajinkyaambatwar** [comment]
Hi @dbczumar , I was trying to run the sklearn_elasticnet_wine project. I created my own copy of the code and run it and got the conda.yaml file generated and created the MLproject file as mentioned in the examples. I am still getting the issue. I checked my mlflow version and it is 1.8 .
I am not using conda and doing everything in python3 virtualenv. 
I tried setting --no-conda flag to try it out. But that doesn't seem to work either. 
Any thing that am I missing?

**Comment by PBenavides** [comment]
> Hi @dbczumar , I was trying to run the sklearn_elasticnet_wine project. I created my own copy of the code and ran it and got the conda.yaml file generated and created the MLproject file as mentioned in the examples. While running "mlflow run", I am still getting the issue. I checked my mlflow version and it is 1.8 .
> I am not using conda and doing everything in python3 virtualenv.
> I tried setting --no-conda flag to try it out. But that doesn't seem to work either.
> Any thing that am I missing?

Same here, did you resolve this? or figured out why this happen?

**Comment by pratiksanjay43** [comment]
Guys just copy the MLproject file from any github repo (for reference: https://github.com/mlflow/mlflow/tree/master/examples) and change as per your configurations.
Make sure that MLproject does not follow any extension, its should just be a file.
