### ISSUE TITLE
[BUG] When running mlflow server with --serve-artifacts args. I am getting error on client side "ValueError: Anonymous credentials cannot be refreshed." 

### ISSUE THREAD

**Issue by iavinas** [mlflow/mlflow#5402]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution Fedora 35**:
- **MLflow installed from binary**:
- **MLflow version 1.23.1**:
- **Python version Python 3.9.5**:
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

I have deployed the mlflow server on a remote host (gke) with the args --serve-artifacts. The pod has the access to read and write to google storage. When running the example code to test if the model file can be uploaded. It is logging metrics but failing to upload files when calling log_artifacts("outputs").

I was expecting artifacts to be uploaded to google cloud without credentials. Interesting thing is that my local system has access to the bucket too.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://github.com/mlflow/mlflow/blob/master/examples/mlflow_artifacts/example.py

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
"ValueError: Anonymous credentials cannot be refreshed." 

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [*] `area/artifacts`: Artifact stores and artifact logging
- [ *] `area/examples`: Example code

**Comment by dbczumar** [comment]
@iavinas Thank you for using `--serve-artifacts`. You're likely seeing this error because the host running `mlflow server` does not have correct / sufficient credentials configured for writing files to Google Cloud Storage. Can you ensure that you've configured such credentials on your host and try again? Feel free to reopen this issue if that does not resolve it.

**Comment by iavinas** [comment]
Yes, the mlflow server pod has admin access to GCS. Manually I can read and write files from the pod using google-cloud-storage.

**Comment by dbczumar** [comment]
@iavinas Can you share a complete traceback for the error?

**Comment by iavinas** [comment]
Hi, @dbczumar yesterday I deleted all the old mlflow==1.21.0 artifacts from my bucket and all projects from the interface. Now I am getting this error I try to call log_artifacts("outputs").

In the URL port is None instead of 80 or nothing.




`Traceback (most recent call last):
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://mlflow.mydomain.com:None/api/2.0/mlflow-artifacts/artifacts/16/eeb1862526c74c14994af6c71a8a2512/artifacts/a.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iavinas/mlflow/test/example.py", line 44, in <module>
    main()
  File "/home/iavinas/mlflow/test/example.py", line 30, in main
    mlflow.log_artifact(tmp_path_a)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 606, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/mlflow/store/artifact/http_artifact_repo.py", line 29, in log_artifact
    resp = self._session.put(url, data=f, timeout=600)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/home/iavinas/miniconda3/lib/python3.9/site-packages/requests/models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://mlflow.mydomain.com:None/api/2.0/mlflow-artifacts/artifacts/16/eeb1862526c74c14994af6c71a8a2512/artifacts/a.txt`

**Comment by D3nn3** [comment]
Can confirm, we're currently trying out `--serve-artifacts` too and are facing the same problem. Access isn't the issue since without the flag and only using `-default-artifact-root` works without any problems (but the client needs GCS authentication which we're trying to avoid).

**Comment by dbczumar** [comment]
@iavinas @D3nn3 Thank you for the clarification. Can you try installing MLflow from the `master` branch? E.g `pip install git+https://github.com/mlflow/mlflow@master`. https://github.com/mlflow/mlflow/pull/5385 was recently merged, which should fix this issue.

**Comment by D3nn3** [comment]
Thank your for the fast answer @dbczumar 

Didn't seem to solve the issue on our end, still get the same error:

`InvalidURL: Failed to parse: http://some-url.com:None/api/2.0/mlflow-artifacts/artifacts/5/f3b7a5a8d58941179ba3208730276cdd/artifacts/training_args.bin`

Here is how we start the server:

```
mlflow server \
    --host=$MLFLOW_HOST \
    --port=$MLFLOW_PORT \
    --workers=$MLFLOW_WORKERS \
    --artifacts-destination="gs://project-name/artifact-store" \
    --backend-store-uri=$MLFLOW_BACKEND_STORE_URI \
    --serve-artifacts
```

**Comment by dbczumar** [comment]
@D3nn3 Can you confirm that you're running the installation from `master` by checking `mlflow.__version__`? It should say `1.23.1.dev0`. I was able to reproduce the `:None` issue on 1.23.1, but it seems to be fixed on `master`.

**Comment by D3nn3** [comment]
It's a bit tricky to verify since we're building docker images and deploying them in Kubernetes.

Output from the CI when building the docker image:
```
Collecting git+https://github.com/mlflow/mlflow@master
  Cloning https://github.com/mlflow/mlflow (to revision master) to /tmp/pip-req-build-agcq3edk
  Running command git clone -q https://github.com/mlflow/mlflow /tmp/pip-req-build-agcq3edk
  Resolved https://github.com/mlflow/mlflow to commit e8db119cc0d5081eea0b06e5b26c94a7193e7336
  Installing build dependencies: started
```

This is the used commit which seems about right: https://github.com/mlflow/mlflow/commit/e8db119cc0d5081eea0b06e5b26c94a7193e7336

Additionally the UI on the deployed service doesn't work anymore and this is the error messages shown in the browser:

```
Unable to display MLflow UI - landing page (index.html) not found.

You are very likely running the MLflow server using a source installation of the Python MLflow
package.

...
```

I assume everything was deployed correctly @dbczumar API endpoints work at least.

**Comment by iavinas** [comment]
@D3nn3 For UI you have to do this either while building docker or before starting Docker build.
`cd mlflow/server/js && \
    npm install && \
    npm run build`

**Comment by iavinas** [comment]
@dbczumar Currently by just installing 1.23.1.dev0 on the client side I am able to upload artifacts. The server is still on 1.23.1 and I am getting this in artifact section of UI- Unable to list artifacts stored under <code>{artifactUri}</code> for the current run.
but the bucket has those files I uploaded.

**Comment by BenWilson2** [comment]
@iavinas that's a different issue with the UI not displaying the artifacts. Our apologies - we're working on it right now: #5393 We're optimistic that all of these bugs will be ironed out for the next release!

**Comment by BenWilson2** [comment]
The second mentioned issue has been resolved in master branch with the merge of #5409
